"""empty message

Revision ID: fca25b8ec70b
Revises: e0e874418ec1
Create Date: 2023-05-31 18:06:29.525937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fca25b8ec70b'
down_revision = 'e0e874418ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)

    # ### end Alembic commands ###