"""empty message

Revision ID: e0e874418ec1
Revises: ffdc0a98111c
Create Date: 2023-05-27 11:03:40.149742

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e0e874418ec1'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('profile_image')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')
    # ### end Alembic commands ###
